#!/usr/bin/env python3
"""Re-derive the separation-of-support results from data/raw/ and compare them
with data/derived/inference.json.

data/derived/inference.json is a DERIVED document: every arm in it names the raw
file and the JSON path it was read from. That makes it mechanically checkable,
and this script checks it in two stages.

  Stage 1 — provenance.  Resolve each arm's `source_path` inside its
  `source_file` and confirm that every non-null n / min_ms / p50_ms / p95_ms /
  p99_ms / max_ms in the derived record is exactly the number sitting in the
  evidence file. A derived document that has drifted from its own sources is
  worse than no derived document at all.

  Stage 2 — arithmetic.  Recompute, from the raw numbers alone:
      support         DISJOINT iff min(slower) > max(faster), else OVERLAPPING
      ratio_interval  [min_slow / max_fast, max_slow / min_fast]
      spans_one       lower bound of that interval <= 1.0
      ratio_of_medians  p50_slow / p50_fast
      permutation denominator  C(n_slow + n_faster, n_slow), and the one-sided
                      exact p-value 1 / C(...) for a disjoint pair
  and fail on any disagreement. The check runs in both directions: a comparison
  the raw data CAN decide must not be published as UNDETERMINABLE, and one it
  cannot decide must not be published as DISJOINT or OVERLAPPING.

The summary block (counts, the spans-1.0 list, the small-n list) is recomputed
from the comparisons and must agree too.

If data/derived/inference.json is absent the script exits 0 with a notice: the
file is generated by a separate process and its absence is not a defect here.

Nothing in this script contacts a database. It cannot tell you whether a number
is TRUE — only whether the document that reasons about it reasons correctly.
"""
from __future__ import annotations

import json
import math
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
DERIVED = REPO / "data" / "derived" / "inference.json"

# `arms.*.results['16x512B|pass1'].update`, `findings[2].evidence.by_document_size['1kb']`
TOKEN = re.compile(
    r"""\s*(?:\.?([A-Za-z_][A-Za-z0-9_\-]*)"""     # .key / key
    r"""|\[\s*(?:'([^']*)'|"([^"]*)"|(\d+))\s*\]"""  # ['key'] / ["key"] / [3]
    r"""|\.?(\*))"""                                  # .*  (single or label-selected child)
)

FIELDS = {
    "n": ("n",),
    "min_ms": ("min_ms", "min"),
    "p50_ms": ("p50_ms", "p50", "median_ms", "median"),
    "p95_ms": ("p95_ms", "p95"),
    "p99_ms": ("p99_ms", "p99"),
    "max_ms": ("max_ms", "max"),
}

DECIDABLE = {"DISJOINT", "OVERLAPPING"}
_cache: dict[str, object] = {}


def load(rel: str):
    if rel not in _cache:
        _cache[rel] = json.loads((REPO / rel).read_text(encoding="utf-8"))
    return _cache[rel]


def parse_path(path: str):
    """Tokenise a source_path, or return None if it is prose rather than a path."""
    tokens, i = [], 0
    while i < len(path):
        match = TOKEN.match(path, i)
        if match is None or match.end() == i:
            return None
        key, sq, dq, index, star = match.groups()
        if key is not None:
            tokens.append(("key", key))
        elif sq is not None:
            tokens.append(("key", sq))
        elif dq is not None:
            tokens.append(("key", dq))
        elif index is not None:
            tokens.append(("index", int(index)))
        else:
            tokens.append(("star", None))
        i = match.end()
    return tokens or None


def resolve(document, tokens, label: str):
    node = document
    for kind, value in tokens:
        if kind == "key":
            if not isinstance(node, dict) or value not in node:
                return None, f"no key {value!r}"
            node = node[value]
        elif kind == "index":
            if not isinstance(node, list) or value >= len(node):
                return None, f"no index [{value}]"
            node = node[value]
        else:  # "star"
            if not isinstance(node, dict):
                return None, "'*' applied to a non-object"
            if len(node) == 1:
                node = next(iter(node.values()))
            else:
                # More than one arm in the file: the derived label must name exactly one.
                hits = [k for k in node if k.lower() in label.lower()]
                if len(hits) != 1:
                    return None, f"'*' ambiguous among {sorted(node)} for label {label!r}"
                node = node[hits[0]]
    return node, None


def close(actual: float, expected: float, tol: float = 1e-9) -> bool:
    return abs(float(actual) - float(expected)) <= tol * max(1.0, abs(float(expected)))


def main() -> int:
    if not DERIVED.is_file():
        print(
            "NOTICE: data/derived/inference.json is not present; "
            "the derived-number check is skipped, not passed."
        )
        return 0

    inference = json.loads(DERIVED.read_text(encoding="utf-8"))
    comparisons = inference.get("comparisons")
    if not isinstance(comparisons, list) or not comparisons:
        print("FAIL: data/derived/inference.json has no 'comparisons' list", file=sys.stderr)
        return 1

    failures: list[str] = []
    unparseable: list[str] = []
    arms_verified = 0

    # ---------- Stage 1: provenance ----------
    for comparison in comparisons:
        cid = comparison.get("id", "<no id>")
        for side in ("slower_arm", "faster_arm"):
            arm = comparison.get(side)
            if not isinstance(arm, dict):
                failures.append(f"{cid}/{side}: missing arm record")
                continue
            source_file = arm.get("source_file")
            source_path = arm.get("source_path")
            if not source_file or not source_path:
                failures.append(f"{cid}/{side}: arm does not name source_file/source_path")
                continue
            if not (REPO / source_file).is_file():
                failures.append(f"{cid}/{side}: source_file {source_file} does not exist")
                continue

            tokens = parse_path(source_path)
            if tokens is None:
                # Prose annotation rather than a machine-readable path (e.g. an arm
                # that produced no observations at all). Reported, never silent.
                unparseable.append(f"{cid}/{side}: {source_file} :: {source_path}")
                continue

            node, error = resolve(load(source_file), tokens, str(arm.get("label", "")))
            if error:
                failures.append(f"{cid}/{side}: {source_file} :: {source_path}: {error}")
                continue

            if isinstance(node, dict):
                for field, spellings in FIELDS.items():
                    derived_value = arm.get(field)
                    if derived_value is None:
                        continue
                    raw_value = next((node[k] for k in spellings if k in node), None)
                    if raw_value is None:
                        failures.append(f"{cid}/{side}: raw record has no {field}")
                    elif not close(raw_value, derived_value):
                        failures.append(
                            f"{cid}/{side}: {field} derived={derived_value!r} "
                            f"raw={raw_value!r} at {source_file} :: {source_path}"
                        )
                arms_verified += 1
            elif isinstance(node, (int, float)) and not isinstance(node, bool):
                published = [v for k, v in arm.items() if k.endswith("_ms") and v is not None]
                if not any(close(node, v) for v in published):
                    failures.append(
                        f"{cid}/{side}: scalar {node!r} at {source_path} matches none of "
                        f"the published values {published!r}"
                    )
                else:
                    arms_verified += 1
            else:
                failures.append(
                    f"{cid}/{side}: {source_path} resolves to {type(node).__name__}, "
                    "not a distribution object or a number"
                )

    # ---------- Stage 2: arithmetic ----------
    recomputed_spans_one: list[str] = []
    small_n: list[str] = []
    counts = {"DISJOINT": 0, "OVERLAPPING": 0, "other": 0}

    for comparison in comparisons:
        cid = comparison.get("id", "<no id>")
        slow, fast = comparison.get("slower_arm", {}), comparison.get("faster_arm", {})
        support = comparison.get("support")

        for arm in (slow, fast):
            n = arm.get("n")
            if isinstance(n, int) and 0 < n < 10:
                small_n.append(cid)
                break

        bounds = (slow.get("min_ms"), slow.get("max_ms"), fast.get("min_ms"), fast.get("max_ms"))
        decidable = all(v is not None for v in bounds)

        if not decidable:
            counts["other"] += 1
            if support in DECIDABLE:
                failures.append(
                    f"{cid}: published support={support} but the raw record lacks "
                    "min and/or max for at least one arm, so separation of support "
                    "cannot be evaluated at all"
                )
            continue

        min_slow, max_slow, min_fast, max_fast = (
            slow["min_ms"], slow["max_ms"], fast["min_ms"], fast["max_ms"],
        )
        expected_support = "DISJOINT" if min_slow > max_fast else "OVERLAPPING"
        counts[expected_support] += 1
        if support != expected_support:
            failures.append(
                f"{cid}: published support={support!r}, recomputed {expected_support!r} "
                f"(min_slow={min_slow}, max_fast={max_fast})"
            )

        lower, upper = min_slow / max_fast, max_slow / min_fast
        interval = comparison.get("ratio_interval")
        if interval is not None:
            if (
                len(interval) != 2
                or abs(round(lower, 4) - interval[0]) > 1e-4
                or abs(round(upper, 4) - interval[1]) > 1e-4
            ):
                failures.append(
                    f"{cid}: ratio_interval published {interval}, "
                    f"recomputed [{lower:.4f}, {upper:.4f}]"
                )

        spans = lower <= 1.0
        if spans:
            recomputed_spans_one.append(cid)
        if comparison.get("spans_one") is not None and comparison["spans_one"] != spans:
            failures.append(
                f"{cid}: spans_one published {comparison['spans_one']}, recomputed {spans} "
                f"(interval lower bound {lower:.4f})"
            )

        if spans == (expected_support == "DISJOINT"):
            failures.append(
                f"{cid}: internally inconsistent — support={expected_support} but the "
                f"ratio interval {'does' if spans else 'does not'} span 1.0"
            )

        p50_slow, p50_fast = slow.get("p50_ms"), fast.get("p50_ms")
        published_ratio = comparison.get("ratio_of_medians")
        if p50_slow and p50_fast and published_ratio is not None:
            recomputed_ratio = p50_slow / p50_fast
            if abs(round(recomputed_ratio, 4) - published_ratio) > 1e-4:
                failures.append(
                    f"{cid}: ratio_of_medians published {published_ratio}, "
                    f"recomputed {recomputed_ratio:.4f}"
                )

        n_slow, n_fast = slow.get("n"), fast.get("n")
        if isinstance(n_slow, int) and isinstance(n_fast, int) and n_slow > 0 and n_fast > 0:
            denominator = math.comb(n_slow + n_fast, n_slow)
            published_denominator = comparison.get("permutation_denominator_C(nA+nB,nA)")
            if published_denominator is not None and published_denominator != denominator:
                failures.append(
                    f"{cid}: permutation denominator published {published_denominator}, "
                    f"recomputed C({n_slow + n_fast},{n_slow}) = {denominator}"
                )
            if expected_support == "DISJOINT":
                one_sided = comparison.get("exact_permutation_p_one_sided")
                if one_sided is not None and not close(one_sided, 1.0 / denominator, 1e-4):
                    failures.append(
                        f"{cid}: exact_permutation_p_one_sided published {one_sided}, "
                        f"recomputed {1.0 / denominator:.6g}"
                    )

    # ---------- Stage 2b: the summary block must match the comparisons ----------
    summary = inference.get("summary")
    if isinstance(summary, dict):
        expected_summary = {
            "n_comparisons": len(comparisons),
            "disjoint": counts["DISJOINT"],
            "overlapping": counts["OVERLAPPING"],
            "undeterminable_or_not_a_latency_comparison": counts["other"],
        }
        for key, expected_value in expected_summary.items():
            if key in summary and summary[key] != expected_value:
                failures.append(
                    f"summary.{key} published {summary[key]}, recomputed {expected_value}"
                )
        if "ratio_interval_spans_1.0" in summary:
            published_set = set(summary["ratio_interval_spans_1.0"])
            recomputed_set = set(recomputed_spans_one)
            if published_set != recomputed_set:
                failures.append(
                    "summary.ratio_interval_spans_1.0 disagrees: only in document "
                    f"{sorted(published_set - recomputed_set)}, only recomputed "
                    f"{sorted(recomputed_set - published_set)}"
                )
        if "claims_resting_on_n_lt_10" in summary:
            published_set = set(summary["claims_resting_on_n_lt_10"])
            recomputed_set = set(small_n)
            if published_set != recomputed_set:
                failures.append(
                    "summary.claims_resting_on_n_lt_10 disagrees: only in document "
                    f"{sorted(published_set - recomputed_set)}, only recomputed "
                    f"{sorted(recomputed_set - published_set)}"
                )

    for item in unparseable:
        print(f"NOT-A-PATH  {item}")
    for item in failures:
        print(f"DISAGREES   {item}")

    if failures:
        print(
            f"\nFAIL: {len(failures)} disagreements between data/derived/inference.json "
            "and the evidence under data/raw/.",
            file=sys.stderr,
        )
        return 1

    print(
        f"OK: {len(comparisons)} comparisons re-derived from data/raw/; "
        f"{arms_verified} arms traced to their source records; "
        f"{counts['DISJOINT']} disjoint, {counts['OVERLAPPING']} overlapping, "
        f"{counts['other']} not decidable from summary statistics; "
        f"{len(unparseable)} arm(s) carry a prose source annotation rather than a path"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
